name: Modern Mythology
favicon: null
layout_spectrum: 1
typography_spectrum: 0.98634
title: "Evan Currie's Corner of the Net"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#0a3033'
    - '#49bedf'
    - '#195e6d'
    - '#fefdfe'
  brandStrength: 1
  lightness: 0.375
  saturation: 0.5
  rhythmicContrast: 0.75
purpose:
  - name: shares
    item: null
    url: null
