name: Modern Mythology
favicon: null
layout_spectrum: 0.03046
typography_spectrum: 0.49265
title: "Evan Currie's Corner of the Net"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#292929'
    - '#fefefe'
    - '#745133'
    - '#858585'
    - '#e0a347'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 1
purpose:
  - name: shares
    item: null
    url: null
